### ISSUE TITLE
Support Spaces

### ISSUE THREAD

**Issue by crstauf** [sindresorhus/macos-wallpaper#32] opened 2020-11-13 03:15 UTC
I have seven spaces defined on my main monitor, and only one path is returned (currently returning the path for the wallpaper on the third space). Would be great if paths for wallpapers on all Spaces was returned!

Possibly related to #25?

**Comment by sindresorhus** [comment] 2020-11-13 13:22
Duplicate of #4

**Closed by sindresorhus** 2020-11-13 13:22 UTC
