### ISSUE TITLE
Setting background color

### ISSUE THREAD

**Issue by arliber** [sindresorhus/macos-wallpaper#26] opened 2019-04-09 11:45 UTC
Hello,
Thanks for making this!
I need to show background images in the center and if they are small enough the solid color blue background shows behind them.

Is there a way to set a color as well? (probably requires setting `NSWorkspaceDesktopImageFillColorKey `)

Thanks!

**Comment by sindresorhus** [comment] 2019-04-09 11:46
Duplicate of #19

**Closed by sindresorhus** 2019-04-09 11:46 UTC
