### ISSUE TITLE
10.14/mojave: set only works on the current desktop

### ISSUE THREAD

**Issue by aerickson** [sindresorhus/macos-wallpaper#23] opened 2019-01-12 01:10 UTC
Expected: `wallpaper set Sierra.jpg` should set the desktop everywhere.
Observed: The command only sets the current desktop's background image.

**Comment by sindresorhus** [comment] 2019-01-12 05:16
I assume you mean that it doesn't set it for other *spaces*, and that's because it's practically impossible. There is a way to do it by listening to space changes and set it then, but that doesn't work for a short-running command-line tool.

**Comment by sindresorhus** [comment] 2019-01-12 05:16
Duplicate of #4

**Closed by sindresorhus** 2019-01-12 05:16 UTC
